name:  Trigger auto-build for pull requests and test if it works properly

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  pull_request:
    branches: 
      [ master ]
    paths:
    - 'survey-app/**'
    - '.github/workflows/survey-ui-AutoDeployTrigger-3b67a214-41f5-4243-99cd-2c155d0270be.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: surveyacr.azurecr.io
          username: ${{ secrets.SURVEYUI_REGISTRY_USERNAME }}
          password: ${{ secrets.SURVEYUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: surveyacr.azurecr.io/survey-ui:${{ github.sha }}
          file: survey-app/Dockerfile
          context: survey-app/
