name: Trigger automated selenium tests 

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  pull_request:
    branches: 
      [ master ]
  push:
    branches: 
      [ master ]
      
    paths:
    - '**'
    - '.github/workflows/survey-ui-AutoDeployTrigger-c6ebdcaf-5925-4e33-8746-835c810ea2ab.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Installed package list
        run: apt list --installed
        
      - name: Install all necessary packages
        run: pip install webdriver-manager selenium
        
      - name: Run the test script
        run: python SurveySaurusLogin.py
