name: Trigger auto deployment for survey-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/survey-ui-AutoDeployTrigger-c6ebdcaf-5925-4e33-8746-835c810ea2ab.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: surveyacr.azurecr.io
          username: ${{ secrets.SURVEYUI_REGISTRY_USERNAME }}
          password: ${{ secrets.SURVEYUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: surveyacr.azurecr.io/survey-ui:${{ github.sha }}
          file: ./Dockerfile
          context: ./

      - name: Dispatch and return Run ID
        uses: codex-/return-dispatch@v1.5.0
        id: return_dispatch
        with:
          token: ${{ secrets.PAT_TOKEN }} # Note this is NOT GITHUB_TOKEN but a PAT
          ref: master
          repo: surveysaurus-qa
          owner: bimser-intern
          workflow: TestTheUI.yml
          workflow_inputs: '{"cake":"delicious"}'
          workflow_timeout_seconds: 100 # Default: 300
          
      - name: Evaluate that the Run ID output has been set
        run: |
          if [ "${{ steps.return_dispatch.outputs.run_id }}" == "" ]; then
            echo "Failed to return Run ID"
            exit 1
          fi
      - name: Output fetched Run ID
        run: echo ${{ steps.return_dispatch.outputs.run_id }}

      - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
        uses: Codex-/await-remote-run@v1.4.0
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repo: surveysaurus-qa
          owner: bimser-intern
          run_id: ${{ steps.return_dispatch.outputs.run_id }}
          run_timeout_seconds: 3000 # Optional
          poll_interval_ms: 5000 # Optional

  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SURVEYUI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n survey-ui -g surveysaurus --server surveyacr.azurecr.io --username  ${{ secrets.SURVEYUI_REGISTRY_USERNAME }} --password ${{ secrets.SURVEYUI_REGISTRY_PASSWORD }}
            az containerapp update -n survey-ui -g surveysaurus --image surveyacr.azurecr.io/survey-ui:${{ github.sha }}
