name: Trigger auto deployment for survey-ui

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'survey-app/**'
    - '.github/workflows/survey-ui-AutoDeployTrigger-5b5daf48-441d-4fb3-870d-aaa1bdda4933.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: surveyacr.azurecr.io
          username: ${{ secrets.SURVEYUI_REGISTRY_USERNAME }}
          password: ${{ secrets.SURVEYUI_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: surveyacr.azurecr.io/survey-ui:${{ github.sha }}
          file: survey-app/Dockerfile
          context: survey-app/


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.SURVEYUI_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n survey-ui -g surveysaurus --server surveyacr.azurecr.io --username  ${{ secrets.SURVEYUI_REGISTRY_USERNAME }} --password ${{ secrets.SURVEYUI_REGISTRY_PASSWORD }}
            az containerapp update -n survey-ui -g surveysaurus --image surveyacr.azurecr.io/survey-ui:${{ github.sha }}
